-- MySQL Script generated by MySQL Workbench
-- Fri Oct 28 09:55:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo` (
  `id` INT NOT NULL,
  `none` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vaga` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `tipo_id1` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vaga_tipo1_idx` (`tipo_id1` ASC) VISIBLE,
  CONSTRAINT `fk_vaga_tipo1`
    FOREIGN KEY (`tipo_id1`)
    REFERENCES `mydb`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliengte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliengte` (
  `rg` INT NOT NULL,
  PRIMARY KEY (`rg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`veiculo` (
  `placa` CHAR NOT NULL,
  PRIMARY KEY (`placa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`locacao` (
  `cliengte_rg` INT NOT NULL,
  `entrada` DATETIME NULL,
  `vaga_id` INT NOT NULL,
  `veiculo_placa` CHAR NOT NULL,
  INDEX `fk_locacao_cliengte_idx` (`cliengte_rg` ASC) VISIBLE,
  INDEX `fk_locacao_vaga1_idx` (`vaga_id` ASC) VISIBLE,
  INDEX `fk_locacao_veiculo1_idx` (`veiculo_placa` ASC) VISIBLE,
  CONSTRAINT `fk_locacao_cliengte`
    FOREIGN KEY (`cliengte_rg`)
    REFERENCES `mydb`.`cliengte` (`rg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_vaga1`
    FOREIGN KEY (`vaga_id`)
    REFERENCES `mydb`.`vaga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_veiculo1`
    FOREIGN KEY (`veiculo_placa`)
    REFERENCES `mydb`.`veiculo` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carros` (
  `placa` CHAR NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `modelo` TEXT NOT NULL,
  PRIMARY KEY (`placa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proposta` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `carros_placa` CHAR NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proposta_carros1_idx` (`carros_placa` ASC) VISIBLE,
  CONSTRAINT `fk_proposta_carros1`
    FOREIGN KEY (`carros_placa`)
    REFERENCES `mydb`.`carros` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `rg` INT(20) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `proposta_id` INT NOT NULL,
  `logadouro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rg`),
  INDEX `fk_cliente_proposta1_idx` (`proposta_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_proposta1`
    FOREIGN KEY (`proposta_id`)
    REFERENCES `mydb`.`proposta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` INT(10) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carros_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carros_has_usuario` (
  `carros_placa` CHAR NOT NULL,
  `usuario_rg` INT NOT NULL,
  PRIMARY KEY (`carros_placa`, `usuario_rg`),
  INDEX `fk_carros_has_usuario_usuario1_idx` (`usuario_rg` ASC) VISIBLE,
  INDEX `fk_carros_has_usuario_carros1_idx` (`carros_placa` ASC) VISIBLE,
  CONSTRAINT `fk_carros_has_usuario_carros1`
    FOREIGN KEY (`carros_placa`)
    REFERENCES `mydb`.`carros` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carros_has_usuario_usuario1`
    FOREIGN KEY (`usuario_rg`)
    REFERENCES `mydb`.`usuario` (`rg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`banco` (
  `numero` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agencia` (
  `numero` INT NOT NULL,
  `banco_numero` VARCHAR(45) NOT NULL,
  `banco_numero` INT NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_agencia_banco1_idx` (`banco_numero` ASC) VISIBLE,
  CONSTRAINT `fk_agencia_banco1`
    FOREIGN KEY (`banco_numero`)
    REFERENCES `mydb`.`banco` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` INT(10) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `id` INT NOT NULL,
  `logadouro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NOT NULL,
  `usuario_numero1` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_endereco_usuario1_idx` (`usuario_numero1` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_usuario1`
    FOREIGN KEY (`usuario_numero1`)
    REFERENCES `mydb`.`usuario` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `matricula` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursa` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`unidade` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno_has_unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno_has_unidade` (
  `aluno_matricula` INT NOT NULL,
  `unidade_id` INT NOT NULL,
  PRIMARY KEY (`aluno_matricula`, `unidade_id`),
  INDEX `fk_aluno_has_unidade_unidade1_idx` (`unidade_id` ASC) VISIBLE,
  INDEX `fk_aluno_has_unidade_aluno1_idx` (`aluno_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_unidade_aluno1`
    FOREIGN KEY (`aluno_matricula`)
    REFERENCES `mydb`.`aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_unidade_unidade1`
    FOREIGN KEY (`unidade_id`)
    REFERENCES `mydb`.`unidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`passageiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`passageiro` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `data_nascimento` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`administrador` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exercusao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exercusao` (
  `id` INT NOT NULL,
  `local_partida` VARCHAR(20) NOT NULL,
  `destino` VARCHAR(20) NOT NULL,
  `lugares_total` INT(10) NOT NULL,
  `veiculos` VARCHAR(25) NOT NULL,
  `lugares_ocupados` INT(10) NOT NULL,
  `data_partida` DATETIME(20) NOT NULL,
  `data_chegada` DATETIME(20) NOT NULL,
  `foto` TINYINT NOT NULL,
  `administrador_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_exercusao_administrador1_idx` (`administrador_id` ASC) VISIBLE,
  CONSTRAINT `fk_exercusao_administrador1`
    FOREIGN KEY (`administrador_id`)
    REFERENCES `mydb`.`administrador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reserva` (
  `id` INT NOT NULL,
  `data_reserva` DATETIME(20) NOT NULL,
  `poltrona` INT(20) NOT NULL,
  `passageiro_id` INT NOT NULL,
  `exercusao_id` INT NOT NULL,
  PRIMARY KEY (`id`, `passageiro_id`, `exercusao_id`),
  INDEX `fk_reserva_passageiro1_idx` (`passageiro_id` ASC) VISIBLE,
  INDEX `fk_reserva_exercusao1_idx` (`exercusao_id` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_passageiro1`
    FOREIGN KEY (`passageiro_id`)
    REFERENCES `mydb`.`passageiro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_exercusao1`
    FOREIGN KEY (`exercusao_id`)
    REFERENCES `mydb`.`exercusao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`areasDeConhecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`areasDeConhecimento` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` INT(10) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`editoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`editoras` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `endereço` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`titulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`titulos` (
  `id` INT NOT NULL,
  `exemplar` VARCHAR(45) NOT NULL,
  `areasDeConhecimento_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `editoras_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_titulos_areasDeConhecimento1_idx` (`areasDeConhecimento_id` ASC) VISIBLE,
  INDEX `fk_titulos_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_titulos_editoras1_idx` (`editoras_id` ASC) VISIBLE,
  CONSTRAINT `fk_titulos_areasDeConhecimento1`
    FOREIGN KEY (`areasDeConhecimento_id`)
    REFERENCES `mydb`.`areasDeConhecimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_titulos_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_titulos_editoras1`
    FOREIGN KEY (`editoras_id`)
    REFERENCES `mydb`.`editoras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autores` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`titulos_has_autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`titulos_has_autores` (
  `titulos_id` INT NOT NULL,
  `autores_id` INT NOT NULL,
  PRIMARY KEY (`titulos_id`, `autores_id`),
  INDEX `fk_titulos_has_autores_autores1_idx` (`autores_id` ASC) VISIBLE,
  INDEX `fk_titulos_has_autores_titulos1_idx` (`titulos_id` ASC) VISIBLE,
  CONSTRAINT `fk_titulos_has_autores_titulos1`
    FOREIGN KEY (`titulos_id`)
    REFERENCES `mydb`.`titulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_titulos_has_autores_autores1`
    FOREIGN KEY (`autores_id`)
    REFERENCES `mydb`.`autores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exemplar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exemplar` (
  `id` INT NOT NULL,
  `titulos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_exemplar_titulos1_idx` (`titulos_id` ASC) VISIBLE,
  CONSTRAINT `fk_exemplar_titulos1`
    FOREIGN KEY (`titulos_id`)
    REFERENCES `mydb`.`titulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emprestimo` (
  `id` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `titulos_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `data`, `titulos_id`, `usuario_id`),
  INDEX `fk_titulos_has_usuario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_titulos_has_usuario_titulos1_idx` (`titulos_id` ASC) VISIBLE,
  CONSTRAINT `fk_titulos_has_usuario_titulos1`
    FOREIGN KEY (`titulos_id`)
    REFERENCES `mydb`.`titulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_titulos_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `codigo` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `qtdEstoque` INT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table3` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `id` INT NOT NULL,
  `dataVenda` VARCHAR(45) NOT NULL,
  `nrNF` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `produto_codigo` INT NOT NULL,
  `venda_id` INT NOT NULL,
  `qtdVenda` VARCHAR(45) NULL,
  PRIMARY KEY (`produto_codigo`, `venda_id`),
  INDEX `fk_produto_has_venda_venda1_idx` (`venda_id` ASC) VISIBLE,
  INDEX `fk_produto_has_venda_produto1_idx` (`produto_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_venda_produto1`
    FOREIGN KEY (`produto_codigo`)
    REFERENCES `mydb`.`produto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_venda_venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `mydb`.`venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
