-- MySQL Script generated by MySQL Workbench
-- Fri Oct 28 00:10:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`passageiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`passageiro` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `data_nascimento` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`administrador` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exercusao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exercusao` (
  `id` INT NOT NULL,
  `local_partida` VARCHAR(20) NOT NULL,
  `destino` VARCHAR(20) NOT NULL,
  `lugares_total` INT(10) NOT NULL,
  `veiculos` VARCHAR(25) NOT NULL,
  `lugares_ocupados` INT(10) NOT NULL,
  `data_partida` DATETIME(20) NOT NULL,
  `data_chegada` DATETIME(20) NOT NULL,
  `foto` TINYINT NOT NULL,
  `administrador_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_exercusao_administrador1_idx` (`administrador_id` ASC) VISIBLE,
  CONSTRAINT `fk_exercusao_administrador1`
    FOREIGN KEY (`administrador_id`)
    REFERENCES `mydb`.`administrador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reserva` (
  `id` INT NOT NULL,
  `data_reserva` DATETIME(20) NOT NULL,
  `poltrona` INT(20) NOT NULL,
  `passageiro_id` INT NOT NULL,
  `exercusao_id` INT NOT NULL,
  PRIMARY KEY (`id`, `passageiro_id`, `exercusao_id`),
  INDEX `fk_reserva_passageiro1_idx` (`passageiro_id` ASC) VISIBLE,
  INDEX `fk_reserva_exercusao1_idx` (`exercusao_id` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_passageiro1`
    FOREIGN KEY (`passageiro_id`)
    REFERENCES `mydb`.`passageiro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_exercusao1`
    FOREIGN KEY (`exercusao_id`)
    REFERENCES `mydb`.`exercusao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
