-- MySQL Script generated by MySQL Workbench
-- Thu Oct 27 21:57:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo` (
  `id` INT NOT NULL,
  `none` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vaga` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `tipo_id1` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vaga_tipo1_idx` (`tipo_id1` ASC) VISIBLE,
  CONSTRAINT `fk_vaga_tipo1`
    FOREIGN KEY (`tipo_id1`)
    REFERENCES `mydb`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliengte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliengte` (
  `rg` INT NOT NULL,
  PRIMARY KEY (`rg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`veiculo` (
  `placa` CHAR NOT NULL,
  PRIMARY KEY (`placa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`locacao` (
  `cliengte_rg` INT NOT NULL,
  `entrada` DATETIME NULL,
  `vaga_id` INT NOT NULL,
  `veiculo_placa` CHAR NOT NULL,
  INDEX `fk_locacao_cliengte_idx` (`cliengte_rg` ASC) VISIBLE,
  INDEX `fk_locacao_vaga1_idx` (`vaga_id` ASC) VISIBLE,
  INDEX `fk_locacao_veiculo1_idx` (`veiculo_placa` ASC) VISIBLE,
  CONSTRAINT `fk_locacao_cliengte`
    FOREIGN KEY (`cliengte_rg`)
    REFERENCES `mydb`.`cliengte` (`rg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_vaga1`
    FOREIGN KEY (`vaga_id`)
    REFERENCES `mydb`.`vaga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_veiculo1`
    FOREIGN KEY (`veiculo_placa`)
    REFERENCES `mydb`.`veiculo` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carros` (
  `placa` CHAR NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `modelo` TEXT NOT NULL,
  PRIMARY KEY (`placa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proposta` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `carros_placa` CHAR NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proposta_carros1_idx` (`carros_placa` ASC) VISIBLE,
  CONSTRAINT `fk_proposta_carros1`
    FOREIGN KEY (`carros_placa`)
    REFERENCES `mydb`.`carros` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `rg` INT(20) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `proposta_id` INT NOT NULL,
  `logadouro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rg`),
  INDEX `fk_cliente_proposta1_idx` (`proposta_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_proposta1`
    FOREIGN KEY (`proposta_id`)
    REFERENCES `mydb`.`proposta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `rg` INT NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `cliente_rg` INT(20) NOT NULL,
  PRIMARY KEY (`rg`),
  INDEX `fk_usuario_cliente1_idx` (`cliente_rg` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_cliente1`
    FOREIGN KEY (`cliente_rg`)
    REFERENCES `mydb`.`cliente` (`rg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carros_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carros_has_usuario` (
  `carros_placa` CHAR NOT NULL,
  `usuario_rg` INT NOT NULL,
  PRIMARY KEY (`carros_placa`, `usuario_rg`),
  INDEX `fk_carros_has_usuario_usuario1_idx` (`usuario_rg` ASC) VISIBLE,
  INDEX `fk_carros_has_usuario_carros1_idx` (`carros_placa` ASC) VISIBLE,
  CONSTRAINT `fk_carros_has_usuario_carros1`
    FOREIGN KEY (`carros_placa`)
    REFERENCES `mydb`.`carros` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carros_has_usuario_usuario1`
    FOREIGN KEY (`usuario_rg`)
    REFERENCES `mydb`.`usuario` (`rg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
